import { type GetServerSideProps } from "next";
import { getSession } from "next-auth/react";
import Head from "next/head";
import Image from "next/image";
import Navbar from "~/components/Navbar";

export default function Home() {
  return (
    <>
      <Head>
        <title>Bread</title>
        <meta name="description" content="Generated by Gabriel Pedroza" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div className="absolute mt-10 flex flex-col justify-center text-center align-middle">
        <h1 className="relative right-48 top-12 font-greatvibes text-8xl text-amber-950">
          Bread
        </h1>
        <div className="relative bottom-[20rem] left-16 h-[900px] w-[1200px] -rotate-[15deg] opacity-90 scale-[200%]">
          <Image
            priority
            src={"/bread-logo-bg-removed.png"}
            alt="Bread logo"
            fill
            draggable="false"
          />
        </div>
        <div className="absolute bottom-96 left-96 flex flex-col justify-center align-middle font-serif text-amber-950 opacity-80 backdrop-blur-md backdrop-filter">
          <div className="relative -mb-[2px] w-[700px] rounded-lg rounded-bl-none border-2 border-black bg-mainBackground py-6 text-4xl">
            <h3>An Automation Tool</h3>
          </div>
          <div className="w-[300px] rounded-b-lg border-2 border-black bg-mainBackground py-4 text-3xl">
            <h3>For Engineers</h3>
          </div>
        </div>
      </div>
    </>
  );
}

export const getServerSideProps: GetServerSideProps = async (context) => {
  const session = await getSession(context);
  if (session) {
    return {
      redirect: {
        destination: "/home",
        permanent: false,
      },
    };
  }

  return {
    props: {},
  };
};
