import { type GetServerSideProps } from "next";
import { getSession } from "next-auth/react";
import Head from "next/head";
import Navbar from "~/components/Navbar";

export default function Home() {

  return (
		<>
			<Head>
				<title>Bread</title>
				<meta name="description" content="Generated by Gabriel Pedroza" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Navbar />
			<h1>Bread</h1>
			<h3>An Automation Tool</h3>
			<h3>For Engineers</h3>
		</>
	);
}

export const getServerSideProps: GetServerSideProps = async (context) => {
  const session = await getSession(context);
  if (session) {
    return {
      redirect: {
        destination: "/home",
        permanent: false,
      },
    };
  }

  return {
    props: {},
  };
};